### ISSUE TITLE
Use GitHub release assets

### ISSUE THREAD

**Issue by MartinKavik** [alsuren/cargo-quickinstall#13]
Hi, @alsuren 

Do you plan to use pre-compiled binaries from GitHub releases if they are available?

Examples:
- https://github.com/sagiegurari/cargo-make/releases
- https://github.com/rustwasm/wasm-pack/releases

They often have the "correct name" already and they are `zip` or `tar.gz` packages.

I think it would save some compilation time on your server / waiting time for the user. And perhaps it would allow to offer pre-compiled binaries even for projects with unique build processes that would be painful to integrate to your server build pipeline.

Context:
We would like to use `cargo-quickinstall` in `cargo-make` ([related issue](https://github.com/sagiegurari/cargo-make/issues/442)) and in [MoonZoon](https://github.com/MoonZoon/MoonZoon) CLI.

Thanks!

P.S. What's the best way to follow `cargo-quickinstall` progress when releases are used for binaries?

**Comment by alsuren** [comment]
cargo-quickinstall always uses the default features, and always builds from the source that's available on crates.io.

If you would like to install from your github releases then you should use something like https://github.com/houseabsolute/ubi, I think.

Annoyingly, ubi takes ages to build though, so maybe use `cargo-quickinstall` to bootstrap it ;-)

**Comment by MartinKavik** [comment]
Thanks for explanation and recommendation!
