### ISSUE TITLE
Add cargo plugins to popular-crates.txt

### ISSUE THREAD

**Issue by sagiegurari** [alsuren/cargo-quickinstall#14]
see https://lib.rs/development-tools/cargo-plugins
those are executables you want to support apart of cli. you will have some duplicates but many cargo plugins are missing at the moment due to that.

**Comment by alsuren** [comment]
If you can find a way to get just the 100 most popular cargo plugins then I'd accept a patch to create a `popular-cargo-plugins.txt` and include it everywhere that popular-crates.txt is used. I don't think I want to build all 427 cargo plugins though.

**Comment by sagiegurari** [comment]
you already have a script block for cli, i gave the relevant url for cargo plugins. you can just run it with that no?

**Comment by alsuren** [comment]
That said, I've not refreshed popular-crates.txt in ages, and I'm not sure that popular-crates.txt is strictly the most popular command-line utilities. There might be more popular things on the second page. I guess it would be fine to run the thing from the comment at the top of popular-crates.txt against  https://lib.rs/development-tools/cargo-plugins and then pipe the combined thing though `| sort | uniq` and dump it all on the bottom of popular-crates.txt... you beat me to it.

Can you send me a patch? (preferably one that updates the comment at the top of the file with instructions ;-) )

**Comment by alsuren** [comment]
(I am off to bed now, so I will probably review it tomorrow)
