### ISSUE TITLE
[tiny] document that you can use cargo-binstall or ubi for installing from github releases

### ISSUE THREAD

**Issue by alsuren** [alsuren/cargo-quickinstall#27]
It might be worth talking to the cargo-binstall people about adding the ability to install packages from the cargo-quickinstall github releases for any of the packages that I have built.

**Comment by passcod** [comment]
Hi! I'm a cargo-binstall person! 👋🏻  talk to me

**Comment by alsuren** [comment]
> Hi! I'm a cargo-binstall person! 👋🏻 talk to me

🍾

I will describe the structure of my packages first, and hopefully we can work out whether this is likely to be usable by binstall.

My naming scheme is currently
https://github.com/alsuren/cargo-quickinstall/blob/7d8c7c81615fd082ee45f28070e2dbfd14abb607/cargo-quickinstall/src/main.rs#L268

I do not have any kind of index or list of built packages: just curl with the OPTIONS method of you want to find out whether a tarball exists.

The only time I'm expecting the URL scheme to change is when I move this repo into the cargo-quick org (which I haven't decided how to do yet):
https://github.com/alsuren/cargo-quickinstall/issues/58 . There might be a way to do this backwards-compatibly though. I can also arrange to do this before we start work on binstall, if you want.

My tarballs are relative to the .cargo/bin directory, so paths are just the names of the executables without any directories or anything.

I don't currently update cargo to tell it that I have installed the package. https://github.com/alsuren/cargo-quickinstall/issues/54 . Binstall might have already worked out a good approach to this. I haven't checked.

I currently report all package requests to a stats server on vercel, which lets me work out what packages to build. I suspect that binstall should probably also report stats, so we don't end up with to many holes in our package coverage. Maybe it should also differentiate itself from the cargo-quickinstall client, but we can do that later.

That's all of the relevant info that I can think of. Questions are:

1) is this enough to be useful in binstall?

2) what would the UI look like in binstall? A --quickinstall flag or something? Should it opportunistically check for quickinstall packages if it can't find what the user is asking for, and suggest using the --quickinstall flag?

3) is there anything else that you would need from me (changes to my packaging scheme, for example) that would make binstall's life easier?

4) is it worth pairing on the design for this? We can set up a call on google meet or discord or whatever (Europe/London time zone) if you want.

**Comment by passcod** [comment]
Thank you for the thorough description!

1. is this enough to be useful in binstall?

Absolutely! That will be fairly easy to plug into our package resolution process.

2. what would the UI look like in binstall? A --quickinstall flag or something? Should it opportunistically check for quickinstall packages if it can't find what the user is asking for, and suggest using the --quickinstall flag?

The goal of cargo-binstall is to "do the right thing the first time" so my thinking is that it will go:
- Prefer crate's own builds if available (i.e. if they have binstall metadata in their manifest).
- (when we implement it): prefer crate's own builds auto-discovered from their repo's releases.
- **lookup the package in quickinstall**
- fall back to source install

Maybe there could be a `--quickinstall` flag to force using your builds later.

3. is there anything else that you would need from me (changes to my packaging scheme, for example) that would make binstall's life easier?

No changes, but some kind of archive format guarantee? I see you use tar.gz for now, is that likely to stay? Or what would be the strategy if/when moving to a new archive/compression format. That can be a later concern though.

4. is it worth pairing on the design for this? We can set up a call on google meet or discord or whatever (Europe/London time zone) if you want.

I'm probably not going to start work on this for another month (focusing on watchexec / cargo watch at the moment) but I'll let you know if I need help / to talk :)

**Comment by alsuren** [comment]
> No changes, but some kind of archive format guarantee? I see you use tar.gz for now, is that likely to stay? Or what would be the strategy if/when moving to a new archive/compression format. That can be a later concern though.

I can't imagine ever switching away from .tar.gz unless GitHub get grumpy with me about abusing their service. The orders-of-magnitude speedup that you get by switching away from building from source means that I'm not that interested in chasing micro-optimisations by changing the compression format. I picked gz because I know that every modern tar implementation supports it. I didn't look into what my other choices are for my target platforms, because it doesn't really matter that much.

> I'm probably not going to start work on this for another month (focusing on watchexec / cargo watch at the moment) but I'll let you know if I need help / to talk :)

That's probably a good use of time. Watchexec is my favourite thing ever (and has been since back I was a python dev many years ago - it is one of the first rust-based cli tools that I ever used, and the first that made it into my regular workflow). Cargo watch is a staple of my workflow now (I often use `cargo watch -c -x fmt -x check` rather than the fmt and check on save functionality built into rust-analyzer). Thank you for all of the time and love that you have poured into them. They are both excellent tools.

**Comment by passcod** [comment]
That's done! cargo-binstall 0.6.2 supports the quickinstall repo. It also sends requests to your stats endpoints, with the user agent `cargo-binstall/0.6.2` (etc)

**Comment by alsuren** [comment]
I have updated the [README](https://github.com/alsuren/cargo-quickinstall/blob/main/README.md). When I make the 0.2.6 release announcement (with --dry-run support), I will recommend people using cargo-binstall for desktop, and `cargo-quickinstall --dry-run` and copy-pasting things into CI pipelines.

**Comment by alsuren** [comment]
@passcod just a heads-up: I have started working on cross-compiling packages for aarch64 linux and macos. People on those platforms should start to see packages appearing over the weekend.

At the moment it's on a "best effort" basis - only packages that can be cross-compiled from ubuntu-20.04 with rustup.
