### ISSUE TITLE
Survive when jq is missing. 

### ISSUE THREAD

**Issue by edfloreshz** [alsuren/cargo-quickinstall#4]
The crate fails to install crate `sensei`, which is only hosted in crates.io. 

Error message: 
```bash
"set -euo pipefail && curl --user-agent \'cargo-quickinstall build pipeline (alsuren@gmail.com)\' --location --fail \'https://crates.io/api/v1/crates/sensei\' | jq -r .versions[0].num" => Output {
    status: ExitStatus(
        ExitStatus(
            32512,
        ),
    ),
    stdout: "",
    stderr: "bash: jq: command not found\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 13927  100 13927    0     0  36080      0 --:--:-- --:--:-- --:--:-- 35987\n(23) Failed writing body\n",
}
Error: Custom { kind: Other, error: "Command failed" }
```
OS: macOS Big Sur 11.0.1

I believe the issue originates in the `get_latest_version()` function, which uses `jq` as a dependency, perhaps you could send better error messages or even better, give the user an option to install these dependencies automatically.

**Comment by alsuren** [comment]
Thanks for raising the issue.

I actually had a thought about how to remove the jq requirement entirely, by making my stats-gathering server do a bit more of the work. I will have a crack at this tomorrow, and cut another release when I have something working.

**Comment by edfloreshz** [comment]
I actually encountered a similar issue with a crate of mine, I implemented a way of getting the JSON without jq. 

```rust
use isahc::{Error, ResponseExt}; 
use serde::{Deserialize, Serialize}; 

#[derive(Serialize, Deserialize)]
struct Crate {
    #[serde(rename = "crate")]
    crt: NewestVersion,
}

#[derive(Serialize, Deserialize)]
struct NewestVersion {
    newest_version: String,
}

fn get_crate_latest_version(crate_name: &String) -> Result<String, Error> {
    let uri = &*format!("https://crates.io/api/v1/crates/{}", crate_name);
    let mut response = isahc::get(uri)?;
    let json = response.text()?;
    let c: Crate = serde_json::from_str(&*json).unwrap();
    Ok(c.crt.newest_version)
}
```

Hope this helps!

**Comment by alsuren** [comment]
I'm currently trying really hard to keep my bootstrapping time down. I suspect that adding serde as a dependency will make `cargo install cargo-quickinstall` take to long. It might have to wait until I have a 2-stage bootstrapping process.

**Comment by edfloreshz** [comment]
Already pushed changes, [PR](https://github.com/alsuren/cargo-quickinstall/pull/5) awaiting for review.

**Comment by edfloreshz** [comment]
After merging [this](https://github.com/alsuren/cargo-quickinstall/pull/6) you may close this issue.

**Comment by alsuren** [comment]
Nice work. Thanks for your help.
