### ISSUE TITLE
Add LICENSE files to repo

### ISSUE THREAD

**Issue by LovecraftianHorror** [alsuren/cargo-quickinstall#76]
I see `cargo-quickinstall`'s `Cargo.toml` lists `"MIT OR Apache-2.0"` for the license. It would be nice to have the LICENSE files added to the repo as well, just to make things more clear

**Comment by alsuren** [comment]
Hi. Thanks for raising the issue. I probably won't get around to it this month, but if it's blocking you then I'll happily review a pull request.

**Comment by LovecraftianHorror** [comment]
I appreciate you letting me know that you're busy. Pull request opened!
