### ISSUE TITLE
Binary release pipeline is broken

### ISSUE THREAD

**Issue by GNQG** [alsuren/cargo-quickinstall#90]
Any actions for binary releases have been failing for days.
This is likely caused by recent changes for [build-version.sh](https://github.com/alsuren/cargo-quickinstall/blob/main/build-version.sh). `set -u` does not allow using environment variables sourced via `env` (see actions' logs).

**Comment by alsuren** [comment]
Well that's embarrassing. I added the ALWAYS_BUILD variable to improve my test coverage so I wouldn't break the pipeline by accident.

Just need to declare it at the top of the file (`ALWAYS_BUILD="${ALWAYS_BUILD:-}" or whatever)

Probably want to duplicate the self-build check in CI to run without that variable set as well.

I will try to get to it this weekend.
